### ISSUE TITLE
Sigmoid before classification

### ISSUE THREAD

**Issue by MorPeled** [jamesmullenbach/caml-mimic#20]
Hi,

If I got it right, models.py > ConvAttnPool is the relevant model to the suggested CAML architecture in the article. 
Looking in the forward function, I see that the last action occuring before calculating loss is linear (multiplying by final.weight & adding final.bias):

`        y = self.final.weight.mul(m).sum(dim=2).add(self.final.bias)
`

but theres no sigmoid after that, as suggested in the paper:
![image](https://user-images.githubusercontent.com/48720490/67681360-d9247800-f995-11e9-858e-39a0ebc363c9.png)

What did I miss?

Thanks :-)
Mor

**Comment by sarahwie** [comment]
Happens here: https://github.com/jamesmullenbach/caml-mimic/blob/7d8ce1585e2fe13fbd5e777d2206a82b0086fb1c/learn/training.py#L261
Also see #14
