### ISSUE TITLE
Vector representation of the ICD9 description 

### ISSUE THREAD

**Issue by datduong** [jamesmullenbach/caml-mimic#6]
Hi, from reading through the model.py. I see that the vector embedding of the label descriptions are trained jointly with the rest of the module. So "practically speaking", the 2nd module in section 2.5 of the paper is in fact trained jointly with the 1st module. Is this correct? 

I guess to make the question more clear. When you say "2nd module" in the paper, you do not imply that the 2nd module is trained entirely independently of the "standard" model. Is this correct? 

Thanks for your help.

**Comment by jamesmullenbach** [comment]
Yes, they're trained jointly

**Comment by datduong** [comment]
Thanks.
